# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Cuisines
Cuisine.create(name: 'Punjabi')
Cuisine.create(name: 'Maharashtrian')
Cuisine.create(name: 'Gujrati')
Cuisine.create(name: 'Bengali')
Cuisine.create(name: 'Karnataka')

# Courses
Course.create(name: 'Appetizer')
Course.create(name: 'Beverages')
Course.create(name: 'Breakfast')
Course.create(name: 'Desserts')
Course.create(name: 'Main Course')
Course.create(name: 'Snacks')
Course.create(name: 'Starters')

# Chefs
Chef.create(name: 'Masterchef Ranjeev Kapoor', about: 'Ranjeev Kapoor is the most celebrated face of Indian cuisine today. He is Chef extraordinaire, runs a successful TV Channel ‘FoodFood’, author of best selling cookbooks, restaurateur and winner of several culinary awards! He is living his dream of making Indian cuisine the number one cuisine in the world and empowering Indian women through power of cooking to become self sufficient.', achievement: 'His much awaited book for the International audience ‘How to Cook Indian’ was released on April 1, 2011 at Indique Heights, Wisconsin Circle. The response was absolutely fantastic and very encouraging.\n While in the USA for the book release he appeared on ‘Rachel Ray Show’ which was aired on 14th April, 2011 as also on The 10! Show on NBC Philly.')

Chef.create(name: 'Chef Kripal Singh Sokhi', about: 'Host of the show Turban Tadka', achievement: 'Fusion of Indian food with international cuisine is what made Chef Kripal Singh Sokhi a name to reckon with in the hotel industry. Hailing from North India, Chef Kripal is a music lover and is fluent in English and five Indian languages - Hindi, Punjabi, Bengali, Oriya and Telugu.')

Chef.create(name: 'Chef Vijay Chopra', about: 'Having worked in London and had great exposure to the International restaurant scene, Vijay brings a refreshing approach to Indian food culture.', achievement: 'With his culinary creativity and true passion for food, Chef Vijay Chopra has worked in some of the most prestigious names around the world like Gordon Ramsay and Angela Harn. Chef Vijay is currently the Executive Chef at the Westin Mumbai Garden City')

Chef.create(name: 'Chef Vipra Dhanna', about: 'Winner of Masterchef 2.\n Anchor of Pure Sin and K for Kids.', achievement: '')

Chef.create(name: 'Chef Veeransh Goila', about: 'Veeransh’s first taste of television success began when he tried out and won a spot on FOOD FOOD Maha Challenge, hosted by Sanjeev Kapoor and Madhuri Dixit. Veeransh went on to win the coveted title of India Ka Super Chef.Veeransh is now the Resident Food Editor with the channel FOODFOOD.', achievement: 'Veeransh was a food enthusiast at an early age, making his first Jalebi for his family at the age of 12.  He continued dabbling in the kitchen while also enrolling in the Barry John Acting School as he had Bollywood dreams as well.  Through the encouragement of his family, especially his Mother, he was drawn more and more into the culinary field as his passion for food grew.His specialty is contemporary Indian food, with varied knowledge of Italian food & bakery and confectionery as well.')

Chef.create(name: 'Chef Arpita Raichand', about: 'MUMMY KA MAGIC hosted by Arpita Raichand \n This 30-minute show features an endearing way to win over the hearts and tummies of tiny tots. Amrita makes nutritious yet tasty and appealing dishes for children who fuss while eating, be it from boredom with their daily meals or dislike of certain vegetables and foods. The show helps parents who do not want to get into the habit of forcing their fussy kids to eat and also those concerned about providing nutritious food for their children. The recipes of Mummy Ka Magic are made using healthy ingredients such as mushrooms, broccoli, zucchini, cheese etc. And since the recipes are prepared for kids, there is lot of focus on presentation which is visually appealing for children.', achievement: 'Ms. Arpita Raichand is a model turned actor. She is a much known face in the Advertising fraternity, best known as the Brand Ambassador for “Whirlpool Home Appliances”. Anchoring a number of game shows on TV and Hosting award functions like the WOW Awards, Big Nite, ACE TECH Awards for builders and many more, she has also set the ramp on fire with her million dollar smile.')

# Shows
Show.create(name: 'Sunny Side Up', day_of_telecast: 'Monday', time_of_telecast: Time.now, description: '')
Show.create(name: 'K for Kids', day_of_telecast: 'Sunday', time_of_telecast: Time.now, description: ' K for Kids is all about experiencing happy and joyful cooking, where kids learn to cook and appreciate their moms role in the kitchen in a fun way with Chef Shipra Khanna.')
Show.create(name: 'Health Magzine', day_of_telecast: 'Thursday', time_of_telecast: Time.now, description: 'This season Health Mange More is headed for a fresh look. The young, energetic and fit Chef Saransh teams up with some of the country’s leading nutritionists to boost your health quotient, like never before. This team of specialists have worked hard to address the nation’s most pressing urban health needs, to serve you nutritious, tasty solutions that will leave you begging for more.
From traditional Indian favourites like Paneer Tikka Masala and Almond Halwa to international delicacies like Mexican Tortilla Wraps, Italian Lasagna and American Chicken Pie, this Health Mange More Team have left no stone unturned in putting a healthy spin on popular treats… And if that’s not enough… every episode packs in some juicy nuggets of food wisdom, peppered with fitness fundas and myth-busting magic to make that power-packed formula fit for a disease-free, urban lifestyle.. all pieced together on a smoking hot and healthy show by the new host Sunanda Ezra Wong.')
Show.create(name: 'India Unlimited', day_of_telecast: 'Thursday', time_of_telecast: Time.now, description: 'Food Food’s Chef Shantanu takes you through the varied tastes of India , its traditions , its color and brings it all together in his kitchen . His cooking tips and tricks, food secrets of recipes that are simple will make you wonder how the complex layers of taste and flavors may have been arrived at! So if you want to explore the rich Malabar Meal , or the traditional Tamil Tiffins, Kashmir’s Kabargah or Goa’s love for vinegar , meat or spices then just head over to Chef Shantanu laying a delectable spread of the state of food affairs in INDIA UNLIMITED')
Show.create(name: 'Sanjeev Kapoor’s Kitchen', day_of_telecast: 'Thursday', time_of_telecast: '3:00 pm', description: 'Sanjeev Kapoor’s top 100 recipes. In this Unique show Master Chef Sanjeev Kapoor will teach the nation his top 100 recipes. From main course to starters, it will feature his best signature dishes.')
Show.create(name: 'Cook Smart', day_of_telecast: 'Monday-Friday', time_of_telecast: Time.now, description: 'The show is packed with simple and smart recipes. It teaches to cook light and healthy meals in easier yet exotic ways. The chef will also share interesting tips on how to cook smart in the kitchen and have a happier life. The show has various types of recipes cooked smartly using Indian spices. MasterChef Sanjeev Kapoor will help you give up on the unhealthy food you love and make you fall in love with your kitchen to cook nutritional food and remain healthy.')
Show.create(name: 'Firangi Tadka', day_of_telecast: 'Sunday', time_of_telecast: Time.now, description: 'Firangi Tadka will present international food using locally available ingredients! From red bean soups to mouth watering Italian pastas, all will be made easy, local and accessible. The show will also be a window into the culture and traditions of the cuisines…and make viewers travel around the world without ever leaving their kitchen!')
Show.create(name: 'Mummy Ka Magic', day_of_telecast: 'Friday', time_of_telecast: Time.now, description: 'Here is a show that every mother can learn from. Mummy Ka Magic has yummylicious  solutions for the biggest problem in a mother’s life – feeding healthy food to their kids. From snacks to desserts that look good, taste good and still have all the essential nutrients required for a child, this show will feature all kinds of fun food that kids and their friends will love and Mothers will love making!')
Show.create(name: 'Turban Tadka', day_of_telecast: 'Monday to Wednesday', time_of_telecast: Time.now, description: 'The Taste of India! This show is all about maa ki daal and Indian desi cuisine! Chef Harpal Singh Sokhi, known as the most entertaining and energetic chef, takes you on a gastronomic journey in a fun and lively manner. Rustic and rooted deep within Indian traditions, Chef Sokhi cooks up some mouth watering desi cuisine!')
Show.create(name: 'The Pooja Makhija Show', day_of_telecast: 'Friday', time_of_telecast: Time.now, description: 'Sick of weighing scales? Want to chuck your measuring tape? We all try to mould ourselves into the cover page figure, the filmy size-zero, the athletic frame or the macho man physique… but there’s only one look that fits us right. That’s the look that keeps you fit on the inside and outside. She’s sold it to corporate honchos … delivered Bollywood A-listers glamourous box office avataars… given sports personalities a winning adrenalin boost … now she’s gearing up to show you how it’s done.. EAT your way to a thinner, healthier, smarter looking you. Watch renowned dietician Pooja Makhija give you the low down on how to eat to your hearts content, while you delete all excess baggage and come through nourished… mind, body and tummy. And if health is not your language trust actor and TV host Vishaal Malhotra to cut through the jargon and add his own brand of humour and drama to the winning formula. So Eat.to.Delete…with The Pooja Makhija Show.')
